/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#4a5e00",
        "on-secondary-container": "#d0d0d0",
        "secondary": "#e2e2e2",
        "surface": "#0e0e0e",
        "surface-bright": "#2c2c2c",
        "surface-dim": "#0e0e0e",
        "on-background": "#ffffff",
        "inverse-on-surface": "#565554",
        "on-secondary-fixed": "#3e4040",
        "surface-container-high": "#201f1f",
        "primary-fixed": "#cafd00",
        "on-primary-fixed-variant": "#526900",
        "on-error": "#450900",
        "inverse-surface": "#fcf8f8",
        "tertiary-container": "#edeaea",
        "secondary-dim": "#d4d4d4",
        "tertiary-fixed": "#ffffff",
        "inverse-primary": "#516700",
        "on-tertiary-fixed-variant": "#6e6d6d",
        "outline-variant": "#494847",
        "on-tertiary-fixed": "#515050",
        "error-container": "#b92902",
        "primary-container": "#cafd00",
        "surface-container-low": "#131313",
        "on-secondary-fixed-variant": "#5a5c5c",
        "tertiary-dim": "#edeaea",
        "surface-container-highest": "#262626",
        "background": "#0e0e0e",
        "surface-container": "#1a1919",
        "outline": "#777575",
        "primary": "#f3ffca",
        "primary-fixed-dim": "#beee00",
        "on-primary-fixed": "#3a4a00",
        "primary-dim": "#beee00",
        "secondary-fixed": "#e2e2e2",
        "surface-tint": "#f3ffca",
        "on-surface": "#ffffff",
        "on-tertiary": "#605f5e",
        "on-tertiary-container": "#575656",
        "on-secondary": "#505252",
        "error-dim": "#d53d18",
        "secondary-fixed-dim": "#d4d4d4",
        "tertiary": "#fcf9f8",
        "tertiary-fixed-dim": "#f3f0ef",
        "on-surface-variant": "#adaaaa",
        "surface-variant": "#262626",
        "secondary-container": "#454747",
        "surface-container-lowest": "#000000",
        "error": "#ff7351",
        "on-error-container": "#ffd2c8",
        "on-primary": "#516700"
      },
      fontFamily: {
        "headline": ["Lexend"],
        "body": ["Inter"],
        "label": ["Space Grotesk"]
      },
      borderRadius: { "DEFAULT": "0px", "lg": "0px", "xl": "0px", "full": "9999px" },
    },
  },
  plugins: [],
}
