/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Romain DI CORATO (https://sketchfab.com/dicorato.romain)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/adidas-ozweego-c072600d2c5a4fd29758d52ef5d0ae90
Title: Adidas Ozweego
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function HeroShoe({ primaryColor = "#000000", secondaryColor = "#ffffff", ropeColor = "#F3FFCA", ...props }) {
  const { nodes, materials } = useGLTF('/models/nike.glb')


  const customMaterials = {
    ...materials
  }

  const testColor = "#FF0000"

  customMaterials.material_grund.color.set(secondaryColor)
  customMaterials.nike_logga.color.set(primaryColor)
  customMaterials.baksida_logga.color.set(primaryColor)
  customMaterials.framsida.color.set(secondaryColor)
  customMaterials.verdel.color.set(secondaryColor)
  customMaterials.framsida_vre.color.set(secondaryColor)
  customMaterials.sko_sula_underdel.color.set(primaryColor)
  customMaterials.sko_sula_sida.color.set(primaryColor)
  customMaterials.sko_sula_framifrn.color.set(primaryColor)
  customMaterials.metall_svart.color.set(secondaryColor)

  //rope color
  customMaterials['Material.006'].color.set(secondaryColor)
  customMaterials['Material.004'].color.set(ropeColor)
  customMaterials['Material.001'].color.set(ropeColor)
  customMaterials['Material.003'].color.set(ropeColor)
  customMaterials.Material.color.set(ropeColor)

  customMaterials.sula_insida.color.set(secondaryColor)

  return (
    <group  {...props} dispose={null}>
      <group scale={0.108}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_17.geometry}
          material={customMaterials.material_grund}

        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_18.geometry}
          material={customMaterials.nike_logga}

        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_19.geometry}
          material={customMaterials.baksida_logga}


        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_20.geometry}
          material={customMaterials.framsida}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_21.geometry}
          material={customMaterials.verdel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_22.geometry}
          material={customMaterials.framsida_vre}
        />
      </group>
      <group scale={0.108}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_24.geometry}
          material={customMaterials.sko_sula_underdel}

        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_25.geometry}
          material={customMaterials.sko_sula_sida}

        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_26.geometry}
          material={customMaterials.sko_sula_framifrn}

        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_5.geometry}
        material={customMaterials.metall_svart}
        position={[0.067, 0.044, -0.048]}
        rotation={[-3.008, -0.005, -2.218]}
        scale={[-0.01, 0.01, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_7.geometry}
        material={customMaterials['Material.006']}
        scale={[0.11, 0.108, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_9.geometry}
        material={customMaterials['Material.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_11.geometry}
        material={customMaterials['Material.001']}
        scale={0.108}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_13.geometry}
        material={customMaterials.Material}
        scale={0.108}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_15.geometry}
        material={customMaterials['Material.003']}
        position={[0.017, 0.116, -0.112]}
        rotation={[0.045, -0.145, 0.007]}
        scale={[0.108, 0.108, 0.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_28.geometry}
        material={customMaterials.sula_insida}
        scale={[0.11, 0.108, 0.108]}
      />
    </group>
  )
}

export default HeroShoe
useGLTF.preload('/models/nike.glb')
